### PR TITLE
Adds support for cljs testing and ->styled tests

### PR DESCRIPTION
**Pull request by brianium**
@roman01la sorry for the delay - I've been busy

This is my first crack at introducing an environment for testing ClojureScript aspects of cljss.

It includes tests for `->styled` to start, and includes a `lein test-all` task for running all tests, as well as a [doo](https://github.com/bensu/doo) setup to test ClojureScript.

I am attempting to get phantomjs installed via Circle CI as well.

Please let me know if you have comments/questions :)

### CODE REVIEW

**Comment by brianium** [comment]
It looks like I can't see what is happening in Circle CI - so I can't tell if what I did works

**Comment by roman01la** [comment]
@brianium Have you seen headless Chrome? It seems like a good new replacement for PhantomJS https://github.com/GoogleChrome/puppeteer

**Comment by roman01la** [comment]
All tests are passed! :) CI link https://circleci.com/gh/roman01la/cljss

**Comment by brianium** [comment]
@roman01la awesome! thank you! I actually used headless Chrome and puppeteer this week for a small application. Definitely an awesome tool 👍  

For the time being - it looks like we are at the mercy of the doo library. In terms of headless browsers, it looks like it only supports phantomjs, slimer, and has some alpha support for electron.

**Pull request merged**
