### PR TITLE
Adds tests for build-styles function

### PR DESCRIPTION
**Pull request by brianium**
@roman01la - maybe I can hold off until I have more complete coverage. It's just hard to keep up with you 😄 

I am pretty interested in the long term health of this project - so I have set aside time to work on this throughout the week. Tests should make it easier to refactor and make sense of things as the library grows 🤷‍♂️ 

I figured a complete test on any public function is still valuable, so I figured I would open this and get your thoughts.

### CODE REVIEW

**Comment by brianium** [comment]
This PR includes a complete test for the `build-styles` function only. As more coverage is added it might be cool to get these running against circle-ci.

**Comment by roman01la** [comment]
Oh wow, that's great! I'll look into Circle CI

**Comment by roman01la** [comment]
FYI: I'm aware there's snapshot (expectation) testing library for Clojure, you might want use it if you like Jest from JavaScript world.

**Comment by roman01la** [comment]
@brianium I just added the project to Circle CI https://circleci.com/gh/roman01la/cljss

**Comment by brianium** [comment]
@roman01la awesome! thanks!

**Pull request merged**
